### ISSUE TITLE
Integração do Template:

### ISSUE THREAD

**Issue by Flashvolve** [Flashvolve-Automacao-Criativa/background_cut#2]
- [x] 1. Puxar o template para o projeto.
- [x] 2. Configurar o layout e rotas principais (ex.: Dashboard, Login, Página 404).

**Comment by Flashvolve** [comment]
Descrição: Incorporar o template ao projeto e configurar o layout e rotas principais.
Resultado Esperado: Layout do template adaptado e rotas essenciais (Dashboard, Login e Página 404) funcionando conforme o projeto.

**Comment by kbrito504** [comment]
# Tarefas de Integração do Template

1. **Tarefa:** Puxar o template para o projeto.  
   **Descrição:** Incorporar o template ao projeto e configurar o layout e rotas principais.  
   **Resultado Esperado:** Layout do template adaptado e rotas essenciais (Dashboard, Login e Página 404) funcionando conforme o projeto.

   **Progresso:**  
   - O layout do template foi adaptado ao projeto.
   - As rotas principais, incluindo a de *catch 404*, estão funcionando como esperado.
   - Como próximo passo, será realizada a implementação das views de autenticação para complementar a estrutura inicial de rotas.

**Comment by kbrito504** [comment]
### Issue Concluída ✅

O template foi integrado com sucesso ao projeto, atendendo às principais funcionalidades e estrutura solicitadas. 🎉

**Tarefas Concluídas:**
1. **Dashboard** 📊: Página principal integrada, aguardando apenas as métricas e insights necessários para a apresentação final.
2. **Uploader** 📤: Implementado conforme a visualização atual do cliente, incluindo funcionalidades de upload, remoção e download em escala para customizações enviadas.
3. **History** 📜: Página de histórico integrada, permitindo a visualização de customizações anteriores e operações associadas.
4. **Autenticação** 🔒: Páginas de login e demais fluxos de autenticação configurados.
5. **Página 404** 🚫: Tela para erros de navegação adicionada.

**Outros Recursos Integrados:**
- **Suporte mobile** 📱: Interface responsiva pronta para uso em dispositivos móveis.
- **Tema e idiomas** 🌗🌐: Alternância entre temas claro e escuro; suporte para português e inglês.

A issue foi finalizada e todas as páginas principais estão configuradas conforme solicitado. 🚀✨
