### ISSUE TITLE
Setup de Backend e Banco de Dados:

### ISSUE THREAD

**Issue by Flashvolve** [Flashvolve-Automacao-Criativa/background_cut#4]
- [ ] Configurar o backend com banco de dados.
- [ ] Criar as tabelas iniciais para usuários, imagens, planos e transações.

**Comment by Flashvolve** [comment]
Descrição: Configurar o backend e o banco de dados, criando as tabelas principais (usuários, imagens, planos e transações).
Resultado Esperado: Estrutura de banco de dados pronta e conectada ao backend, com endpoints básicos testados.

**Comment by Flashvolve** [comment]
### **Tabelas Principais**

1. **users**  
   - **Descrição**: Armazena informações dos usuários do sistema.
   - **Campos**:
     - `id` (PK) – UUID: Identificador único do usuário.
     - `name` – VARCHAR(100): Nome do usuário.
     - `email` – VARCHAR(100), único: Email para login e notificações.
     - `password_hash` – VARCHAR(255): Hash da senha para autenticação.
     - `role` – ENUM('user', 'admin'): Define o nível de acesso.
     - `plan_id` (FK) – Referência para `plans`: Plano de assinatura atual do usuário.
     - `credits` – INT: Saldo de créditos para uso, caso o sistema use créditos.
     - `created_at` – TIMESTAMP: Data de criação da conta.
     - `updated_at` – TIMESTAMP: Data de última atualização.

2. **plans**  
   - **Descrição**: Define os planos de assinatura disponíveis.
   - **Campos**:
     - `id` (PK) – UUID: Identificador do plano.
     - `name` – VARCHAR(50): Nome do plano (ex.: Básico, Pro).
     - `price` – DECIMAL(10, 2): Preço do plano.
     - `image_limit` – INT: Limite de imagens por mês.
     - `credit_limit` – INT: Créditos por mês (caso o plano use créditos).
     - `features` – JSON: Lista de funcionalidades extras incluídas.
     - `created_at` – TIMESTAMP: Data de criação do plano.
     - `updated_at` – TIMESTAMP: Data de última atualização.

3. **subscriptions**  
   - **Descrição**: Registra informações de assinaturas dos usuários.
   - **Campos**:
     - `id` (PK) – UUID: Identificador único da assinatura.
     - `user_id` (FK) – Referência para `users`: ID do usuário associado.
     - `plan_id` (FK) – Referência para `plans`: ID do plano assinado.
     - `status` – ENUM('active', 'inactive', 'canceled'): Status atual da assinatura.
     - `start_date` – DATE: Data de início da assinatura.
     - `end_date` – DATE: Data de término ou renovação.
     - `renewal_date` – DATE: Data da próxima renovação.
     - `created_at` – TIMESTAMP: Data de criação da assinatura.
     - `updated_at` – TIMESTAMP: Data de última atualização.

4. **images**  
   - **Descrição**: Armazena informações de cada imagem processada.
   - **Campos**:
     - `id` (PK) – UUID: Identificador da imagem.
     - `user_id` (FK) – Referência para `users`: ID do usuário proprietário.
     - `original_url` – VARCHAR(255): URL da imagem original.
     - `processed_url` – VARCHAR(255): URL da imagem após processamento.
     - `status` – ENUM('pending', 'processed', 'failed'): Status do processamento.
     - `upload_date` – TIMESTAMP: Data e hora de upload da imagem.
     - `edited_at` – TIMESTAMP: Última data de edição da imagem.
     - `tags` – JSON: Tags associadas à imagem para organização.

5. **image_edits**  
   - **Descrição**: Registra as edições feitas em cada imagem.
   - **Campos**:
     - `id` (PK) – UUID: Identificador da edição.
     - `image_id` (FK) – Referência para `images`: ID da imagem editada.
     - `edit_type` – ENUM('contrast', 'brightness', 'resize', 'crop', 'background_change', 'manual_adjustment'): Tipo de edição realizada.
     - `parameters` – JSON: Parâmetros específicos da edição (ex.: nível de contraste).
     - `edit_date` – TIMESTAMP: Data e hora da edição.

6. **payments**  
   - **Descrição**: Registra informações de pagamentos de assinatura e renovações.
   - **Campos**:
     - `id` (PK) – UUID: Identificador do pagamento.
     - `user_id` (FK) – Referência para `users`: ID do usuário que fez o pagamento.
     - `subscription_id` (FK) – Referência para `subscriptions`: ID da assinatura paga.
     - `amount` – DECIMAL(10, 2): Valor do pagamento.
     - `status` – ENUM('completed', 'pending', 'failed'): Status da transação.
     - `payment_date` – TIMESTAMP: Data do pagamento.
     - `method` – ENUM('credit_card', 'paypal', 'bank_transfer'): Método de pagamento usado.

---

### **Tabelas de Suporte e Funcionalidades Avançadas**

1. **support_tickets**  
   - **Descrição**: Registra tickets de suporte abertos pelos usuários.
   - **Campos**:
     - `id` (PK) – UUID: Identificador do ticket.
     - `user_id` (FK) – Referência para `users`: ID do usuário que abriu o ticket.
     - `subject` – VARCHAR(100): Assunto do ticket.
     - `description` – TEXT: Descrição detalhada do problema.
     - `status` – ENUM('open', 'in_progress', 'closed'): Status do ticket.
     - `created_at` – TIMESTAMP: Data de abertura do ticket.
     - `updated_at` – TIMESTAMP: Data de última atualização do ticket.

2. **faqs**  
   - **Descrição**: Tabela de artigos e FAQs para a central de ajuda.
   - **Campos**:
     - `id` (PK) – UUID: Identificador do artigo.
     - `title` – VARCHAR(100): Título do artigo ou FAQ.
     - `content` – TEXT: Conteúdo do artigo.
     - `category` – ENUM('getting_started', 'billing', 'technical', 'other'): Categoria do artigo.
     - `created_at` – TIMESTAMP: Data de criação do artigo.
     - `updated_at` – TIMESTAMP: Data de última atualização.

3. **notifications**  
   - **Descrição**: Armazena notificações enviadas aos usuários.
   - **Campos**:
     - `id` (PK) – UUID: Identificador da notificação.
     - `user_id` (FK) – Referência para `users`: ID do usuário que recebe a notificação.
     - `message` – TEXT: Conteúdo da notificação.
     - `type` – ENUM('credit_alert', 'new_feature', 'billing', 'other'): Tipo da notificação.
     - `status` – ENUM('unread', 'read'): Status de leitura da notificação.
     - `sent_at` – TIMESTAMP: Data e hora de envio da notificação.

4. **api_tokens**  
   - **Descrição**: Tabela para gerenciamento de tokens de API.
   - **Campos**:
     - `id` (PK) – UUID: Identificador do token.
     - `user_id` (FK) – Referência para `users`: ID do usuário proprietário do token.
     - `token` – VARCHAR(255): Chave de acesso para API.
     - `expires_at` – TIMESTAMP: Data de expiração do token.
     - `created_at` – TIMESTAMP: Data de criação do token.

---

### **Tabelas para Administração e Análise**

1. **user_activity_log**  
   - **Descrição**: Armazena registros de atividades para auditoria e segurança.
   - **Campos**:
     - `id` (PK) – UUID: Identificador do log.
     - `user_id` (FK) – Referência para `users`: ID do usuário.
     - `activity_type` – ENUM('login', 'logout', 'edit', 'delete', 'upload'): Tipo de atividade registrada.
     - `details` – JSON: Detalhes específicos da atividade.
     - `activity_date` – TIMESTAMP: Data e hora da atividade.

2. **usage_metrics**  
   - **Descrição**: Tabela para armazenar métricas de uso para relatórios administrativos.
   - **Campos**:
     - `id` (PK) – UUID: Identificador da métrica.
     - `metric_type` – ENUM('images_processed', 'active_users', 'new_signups'): Tipo de métrica.
     - `value` – INT: Valor numérico da métrica.
     - `metric_date` – DATE: Data de registro da métrica.

---

### Resumo da Estrutura

Essa estrutura de banco de dados cobre:
- Gerenciamento de usuários e assinaturas, com detalhamento de planos.
- Processamento e edição de imagens, incluindo histórico de edições.
- Pagamentos e suporte ao cliente, centralizando tickets e artigos de ajuda.
- Funcionalidades avançadas como notificações, tokens de API e logs de atividade.

**Comment by kbrito504** [comment]
### Issue Concluída ✅

A configuração do backend foi concluída com sucesso, utilizando o banco de dados no Supabase (acesso: [Dashboard Supabase](https://supabase.com/dashboard/project/wckhzqvsrbvzktnxeabj/editor)) e implementando um controller para realizar as operações das principais entidades. 🎉

**Tabelas Principais Criadas:**

1. **users** 👤
   - Armazena informações dos usuários do sistema.
   - Campos: `id`, `name`, `email`, `password_hash`, `role`, `plan_id`, `credits`, `created_at`, `updated_at`.

2. **plans** 📊
   - Define os planos de assinatura disponíveis.
   - Campos: `id`, `name`, `price`, `image_limit`, `credit_limit`, `features`, `created_at`, `updated_at`.

3. **subscriptions** 🔄
   - Registra as informações das assinaturas dos usuários.
   - Campos: `id`, `user_id`, `plan_id`, `status`, `start_date`, `end_date`, `renewal_date`, `created_at`, `updated_at`.

4. **images** 🖼️
   - Armazena as informações de cada imagem processada.
   - Campos: `id`, `user_id`, `original_url`, `processed_url`, `status`, `upload_date`, `edited_at`, `tags`.

5. **image_edits** ✏️
   - Registra as edições feitas nas imagens.
   - Campos: `id`, `image_id`, `edit_type`, `parameters`, `edit_date`.

6. **payments** 💳
   - Registra informações sobre pagamentos e renovações de assinatura.
   - Campos: `id`, `user_id`, `subscription_id`, `amount`, `status`, `payment_date`, `method`.

**Recursos Adicionais:**
- **Controller**: Implementado para realizar operações CRUD nas tabelas principais.
- **Suporte a futuras tabelas**: As demais tabelas serão adicionadas conforme o desenvolvimento do projeto.

A issue foi finalizada, com o backend estruturado e pronto para o desenvolvimento das funcionalidades. 🚀
