### ISSUE TITLE
Upload de Imagens:

### ISSUE THREAD

**Issue by Flashvolve** [Flashvolve-Automacao-Criativa/background_cut#5]
- [ ] Adaptar a interface para upload de imagens (com suporte a arrastar e soltar, colagem e seleção de arquivos).
- [ ] Configurar integração com API de remoção de fundo.

**Comment by Flashvolve** [comment]
Descrição: Configurar o backend e o banco de dados, criando as tabelas principais (usuários, imagens, planos e transações).
Resultado Esperado: Estrutura de banco de dados pronta e conectada ao backend, com endpoints básicos testados.

**Comment by kbrito504** [comment]
# Tarefas de Upload de Imagens

1. **Tarefa:** Puxar o template para o projeto.  
   **Descrição:** Incorporar o template ao projeto e configurar o layout e rotas principais.  
   **Resultado Esperado:** Layout do template adaptado e rotas essenciais (Dashboard, Login e Página 404) funcionando conforme o projeto.

   **Progresso:**  
   - O layout do template foi adaptado ao projeto.
   - As rotas principais, incluindo a de *catch 404*, estão funcionando como esperado.
   - Como próximo passo, será realizada a implementação das views de autenticação para complementar a estrutura inicial de rotas.

2. **Tarefa:** Adaptar a interface para upload de imagens.  
   **Descrição:** Implementar suporte a arrastar e soltar, colagem e seleção de arquivos.  
   **Progresso:**  
   - Todas as operações para upload de imagens já estão disponíveis e concluídas.

3. **Tarefa:** Configurar integração com API de remoção de fundo.  
   **Progresso:**  
   - A integração com a API de remoção de fundo foi configurada com sucesso e está disponível.
